### ISSUE TITLE
GUI Paddle OCR Indices for Array Error?

### ISSUE THREAD

**Issue by AziRizvi** [cloudy-sfu/GUI-for-paddlepaddle-OCR#4]
![GUI-for-paddlepaddle-OCR_BvG0QHvQRb](https://github.com/cloudy-sfu/GUI-for-paddlepaddle-OCR/assets/129892077/29721e57-0d19-4646-892f-7eb68a62f5ac)

This is the error it's giving me whenever I try to OCR anything, same error with a single image and same error when I try it out with a folder, the images I'm trying to OCR are in png format.

**Comment by cloudy-sfu** [comment]
Is it still the same pictures as described in the issue in Tesseract?

I suspect it's because these pictures use the transparency channel (alpha channel). Allow me some time to inspect and fix it. Thank you for your feedback!

**Comment by AziRizvi** [comment]
Yes, these are the same images, I've uploaded them on my Github in a repo and linked them in the Tesseract repository.
I thought this issue might be caused because the filenames were too long so I tried to rename them and the result was the same which led me to believe that this is some other issue, then I opened this issue ticket.

**Comment by cloudy-sfu** [comment]
A long filename is OK. I didn't assume any limitations on the filename length, because it's not C language, and I don't have to pre-allocate space manually. I'll inspect it later and will reveal the reason.

**Comment by cloudy-sfu** [comment]
I am glad to announce that I have fixed this problem. At the same time, the paddle OCR v2 model has ended its lifecycle, as the maintenance from the "Baidu" company on v2 has stopped. Therefore, I upgraded to the paddle OCR v4 model.

The recognition workflow is primarily simplified so that fewer problems will occur.

Here is an example of your example data. @AziRizvi 

![image](https://github.com/cloudy-sfu/GUI-for-tesseract-OCR/assets/41314224/e2fe874d-992a-4a89-8000-542316e16649)

Release at:

https://github.com/cloudy-sfu/GUI-for-paddlepaddle-OCR/releases/tag/v0.2.0

I appreciate your patience. Also, please note that the "paddle OCR v4" model supports more than Chinese and English, but I need extra work to build a language switcher (like tesseract OCR).

**Comment by AziRizvi** [comment]
> I am glad to announce that I have fixed this problem. At the same time, the paddle OCR v2 model has ended its lifecycle, as the maintenance from the "Baidu" company on v2 has stopped. Therefore, I upgraded to the paddle OCR v4 model.
> 
> The recognition workflow is primarily simplified so that fewer problems will occur.
> 
> Here is an example of your example data. @AziRizvi
> 
> ![image](https://private-user-images.githubusercontent.com/41314224/296446910-e2fe874d-992a-4a89-8000-542316e16649.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTYxNDEsIm5iZiI6MTcwNTIxNTg0MSwicGF0aCI6Ii80MTMxNDIyNC8yOTY0NDY5MTAtZTJmZTg3NGQtOTkyYS00YTg5LTgwMDAtNTQyMzE2ZTE2NjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA3MDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YzFjN2MwZGNmNDI0NTJkZTAyZTIwMDdkN2E4NWI1MmYxNTk1YzU3MmQ1NGU3MjAyNGY1MGZhZmVjYzk4OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UjM-BMGW33DE7plivwp1u814vNl1tTSiRiAm8AfV5Oo)
> 
> Release at:
> 
> https://github.com/cloudy-sfu/GUI-for-paddlepaddle-OCR/releases/tag/v0.2.0
> 
> I appreciate your patience. Also, please note that the "paddle OCR v4" model supports more than Chinese and English, but I need extra work to build a language switcher (like tesseract OCR).

That is great news!
Thank you for fixing the errors.

I will test things out either today or tomorrow and get back to you soon!

**Comment by cloudy-sfu** [comment]
Known issue:

```
Traceback (most recent call last):
  File "main.pyw", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "ocr.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\__init__.py", line 25, in <module>
    from paddleocr.tools.infer.utility import init_args
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddleocr\tools\infer\utility.py", line 21, in <module>
    import paddle
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddle\__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "paddle\base\__init__.py", line 207, in <module>
  File "paddle\base\__init__.py", line 199, in __bootstrap__
RuntimeError: (PreconditionNotMet) The third-party dynamic library (mklml.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:312)
```

It is scheduled to be fixed soon. Thank you for your patience.

**Comment by cloudy-sfu** [comment]
Fixed (see latest release)
